openapi: 3.0.3
info:
  title: API do ShortsAI Studio
  description: Contrato de API para o backend do gerador de vídeo automatizado ShortsAI.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Servidor de Produção
  - url: http://localhost:3000/api
    description: Desenvolvimento Local

components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        topic:
          type: string
        style:
          type: string
        voice_name:
          type: string
        tts_provider:
          type: string
          enum: [gemini, elevenlabs]
        language:
          type: string
          default: 'en'
        status:
          type: string
          enum: [draft, generating, completed, failed]
        include_music:
          type: boolean
        bg_music_prompt:
          type: string
        bg_music_url:
          type: string
        generated_title:
          type: string
        generated_description:
          type: string
        duration_config:
          type: object
          properties:
            min:
              type: integer
            max:
              type: integer
            targetScenes:
              type: integer
        characterIds:
          type: array
          items:
            type: string
          description: Lista de UUIDs de Personagens usados para consistência visual.
        reference_image_url:
          type: string
          deprecated: true
          description: Use characterIds em vez disso.
        scenes:
          type: array
          items:
            $ref: '#/components/schemas/Scene'
        created_at:
          type: string
          format: date-time
    Scene:
      type: object
      properties:
        id:
          type: string
          format: uuid
        scene_number:
          type: integer
        visual_description:
          type: string
        narration:
          type: string
        duration_seconds:
          type: number
        image_url:
          type: string
        image_status:
          type: string
          enum: [pending, loading, completed, error]
        audio_url:
          type: string
        audio_status:
          type: string
          enum: [pending, loading, completed, error]
    Character:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            type: string
    UserQuota:
      type: object
      properties:
        plan:
          type: string
          enum: [free, pro, enterprise]
        limits:
          type: object
          properties:
            maxVideos:
              type: integer
            maxTTSMinutes:
              type: number
            maxImages:
              type: integer
        used:
          type: object
          properties:
            currentVideos:
              type: integer
            currentTTSMinutes:
              type: number
            currentImages:
              type: integer

paths:
  /users:
    post:
      summary: Criar ou Obter Usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, name]
              properties:
                email:
                  type: string
                name:
                  type: string
                avatar_url:
                  type: string
                google_id:
                  type: string
      responses:
        '200':
          description: Usuário criado ou recuperado
    get:
      summary: Obter usuário por email
      parameters:
        - name: email
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do usuário

  /user/apikeys:
    get:
      summary: Obter Chaves de API do Usuário (Mascaradas/Criptografadas)
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chaves de API mascaradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  gemini_key:
                    type: string
                  elevenlabs_key:
                    type: string
                  suno_key:
                    type: string
    post:
      summary: Salvar Chaves de API do Usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id:
                  type: string
                gemini_key:
                  type: string
                elevenlabs_key:
                  type: string
                suno_key:
                  type: string
      responses:
        '200':
          description: Chaves de API salvas

  /users/quota:
    get:
      summary: Obter Cota de Uso do Usuário
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Estatísticas de uso atuais
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserQuota'

  /usage:
    post:
      summary: Registrar Uso da API (Reportado pelo Cliente)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, action_type, provider]
              properties:
                user_id:
                  type: string
                project_id:
                  type: string
                action_type:
                  type: string
                provider:
                  type: string
                model_name:
                  type: string
                tokens_input:
                  type: integer
                tokens_output:
                  type: integer
                status:
                  type: string
      responses:
        '201':
          description: Log salvo

  /projects:
    get:
      summary: Listar projetos do usuário
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de projetos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      summary: Criar um novo projeto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, topic, style, voice_name]
              properties:
                user_id:
                  type: string
                topic:
                  type: string
                style:
                  type: string
                voice_name:
                  type: string
                tts_provider:
                  type: string
                  enum: [gemini, elevenlabs]
                language:
                  type: string
                include_music:
                  type: boolean
                bg_music_prompt:
                  type: string
                duration_config:
                  type: object
                  properties:
                    min:
                      type: integer
                    max:
                      type: integer
                    targetScenes:
                      type: integer
                characterIds:
                  type: array
                  items:
                    type: string
                  description: Array de UUIDs de Personagens para vincular
      responses:
        '200':
          description: Projeto criado (retorna projeto completo com ID)

  /projects/{id}:
    patch:
      summary: Atualizar detalhes do projeto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Projeto atualizado
    delete:
      summary: Excluir um projeto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Projeto excluído

  /scenes:
    post:
      summary: Criar uma cena
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [project_id, scene_number]
              properties:
                project_id:
                  type: string
                scene_number:
                  type: integer
                visual_description:
                  type: string
                narration:
                  type: string
                duration_seconds:
                  type: number
                image_url:
                  type: string
                audio_url:
                  type: string
      responses:
        '200':
          description: Cena criada

  /scenes/{id}:
    patch:
      summary: Atualizar assets e conteúdo da cena
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                visual_description:
                  type: string
                  description: Prompt visual atualizado
                narration:
                  type: string
                  description: Texto de narração atualizado
                duration_seconds:
                  type: number
                image_url:
                  type: string
                image_status:
                  type: string
                audio_url:
                  type: string
                audio_status:
                  type: string
      responses:
        '200':
          description: Cena atualizada

  /characters:
    get:
      summary: Obter biblioteca de personagens do usuário
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de personagens
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
    post:
      summary: Salvar um novo personagem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [user_id, name, images]
              properties:
                user_id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                images:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Personagem salvo

  /characters/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Personagem excluído